apiVersion: v1
kind: ConfigMap
metadata:
  name: fruit-classifier-config
data:
  S3_BUCKET: "fruit-classifier-model-store"
  MODEL_KEY: "models/best_model.pth"
  DYNAMO_TABLE: "fruit-predictions"
  AWS_REGION: "us-east-1"